### ISSUE TITLE
Interface the servo motor

### ISSUE THREAD

**Issue by mikeshams** [sadgunakarri/capstone-project#6]

**Comment by mikeshams** [comment]
1. What issues did you or others might face with connection of a Servomotor to the BBB in terms of Hardware and software?
2. How do you solve them?

**Comment by Rasan42** [comment]
Sometimes the motor can stop running and will. Not move, therefore i recommend that we should choose a motor which has 50% torque > the actual one..

**Comment by Rasan42** [comment]
Servo motor was restarting Beaglebone when connected to SYS_5V  due to lack of power
 As there's no power indicator, we always needed to recheck whether all connections are right. 
No proper library available for C Programming Language.
 No Proper support by manufacturer for Beaglebone Platform.. No working PWM library was found.

Needed to read the datasheet of servo motor and manually generate pwm signals to operate servo.
