### ISSUE TITLE
Interfacing router to the Beaglebone

### ISSUE THREAD

**Issue by mikeshams** [sadgunakarri/capstone-project#8]

**Comment by mikeshams** [comment]
1. What issues did you or others might face when connection of a WIFI Module to a BBB in terms of hardware and software?
2. How to resolve them?

**Comment by supbhatoa07** [comment]
Answer 1- as we discussed today, we first need to look at the recommended wifi adapters on beaglebone site. If the adapter is listed then you may not need to install an additional drivers for connectivity but if not then you need to. Luckily my beagle bone does not ask for additional drivers because i have latest updated version of debian and i have configured the " connmanctl" file.
Its important to have usb driver in beaglebone to detect adapter, this driver is generally installed by updating the beaglebone image. connecting to hotspot is another problem which we faced.

Answer 2- i use the supo apt - get update command for downloading the drivers and updating the beglebone.Then sudo apt upgrade to install the latest drivers.After that i configured the onnmanctls file.I followed the beaglebone wifi connectivity tutorial for this. the reference is given in ppt
